### ISSUE TITLE
This package is incompatible with MRTK 2.1

### ISSUE THREAD

**Issue by Charles-W4** [microsoft/MixedRealityLearning#16]
I've been following the MRTK tutorials (https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch4). Tutorial 5 has you add this BaseModule package and it is incompatible with MRTK 2.1.

**Comment by mr0ng** [comment]
Yes, this is a known issue and currently being updated to maintain compatibility with the new MRTK

**Comment by Charles-W4** [comment]
Closing this and posting to a more appropriate location: https://github.com/MicrosoftDocs/mixed-reality/issues/1779
