### ISSUE TITLE
some problem in gettingstarted package

### ISSUE THREAD

**Issue by Lloyd0577** [microsoft/MixedRealityLearning#31]
when i import gettingstarted 2.4.0 package ,and after i dragged RoverAssembly prefabs to hierarchy window ,it show nothing  just some cube  ,but  in the tutorials documents it show a mars curiosity, i wander if anything wrong in here ,how can i do,hope for your reply  thanks!

**Comment by martinwilter** [comment]
Hi @Lloyd0577, it should look similar to the image in the tutorial:

![image](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/images/mr-learning-base/base-04-section3-step1-3.png)

Can you share a similar screenshot of your Unity project so we can see what that cube might be?

**Comment by martinwilter** [comment]
Closing this issue since we have not heard back. Feel free to reach out again if you are still facing this issue.
