### ISSUE TITLE
Example crashes in Hololens 2 when clicking the button CreateAzureAnchor

### ISSUE THREAD

**Issue by Efaq** [microsoft/MixedRealityLearning#33]
Hi

I am following the tutorial https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-01 for Multi User capabilities, and I'm facing some issues. I am able to successfully follow the tutorial and execute it until before I come to the Azure Spatial Anchor part. In this part, I follow the instructions, build the project, deploy it to my Hololens 2 and run it. Everything works well until I interact with the button CreateAzureAnchor, when suddenly the application crashes.

In debug mode in Visual Studio 2019 I get the exception:

`Exception thrown at 0x00007FFC1573AA30 (UnityPlayer.dll) in Holo R5 OLD.exe: 0xC0000005: Access violation reading location 0x0000000000000000`

The stack trace looks like the following:

'

UnityPlayer.dll!00007ffc1573aa30()	Unknown
 	UnityPlayer.dll!00007ffc157459ac()	Unknown
>	GameAssembly.dll!WorldAnchor_GetNativeSpatialAnchorPtr_m1075A839F6054A0F6A6AA313B935E889773D6C91(WorldAnchor_tD6275232D14415769601A3BD6AE1E7D5622F96EE * __this, const MethodInfo * method) Line 14661	C++
 	GameAssembly.dll!SpatialAnchorExtensions_GetPointer_m65B5066FC1C218482E5C6D5E27C3530B10D0E0F2(WorldAnchor_tD6275232D14415769601A3BD6AE1E7D5622F96EE * ___anchor0, const MethodInfo * method) Line 23602	C++
 	GameAssembly.dll!U3CCreateAzureAnchorU3Ed__12_MoveNext_m8A44716F855E38951BFA8C44DD9A0262013644B0(U3CCreateAzureAnchorU3Ed__12_tB591518B0F6D6EAF45CD3DE7CA4193BD40AEECD5 * __this, const MethodInfo * method) Line 27906	C++
 	[Inline Frame] GameAssembly.dll!InterfaceActionInvoker0::Invoke(unsigned int) Line 117	C++
 	GameAssembly.dll!AsyncVoidMethodBuilder_Start_TisRuntimeObject_m8590BDB280C38FD9D41163DF39805FFA6EA8F508_gshared(AsyncVoidMethodBuilder_t44E3C9B52B019BB5BDCC0E1BB83188B536161CFF * __this, Il2CppObject * * ___stateMachine0, const MethodInfo * method) Line 36215	C++
 	[Inline Frame] GameAssembly.dll!AsyncVoidMethodBuilder_Start_TisU3CCreateAzureAnchorU3Ed__12_tB591518B0F6D6EAF45CD3DE7CA4193BD40AEECD5_m299A940ADFC49A5F42BBB82A2A7D90D87536B7B5(AsyncVoidMethodBuilder_t44E3C9B52B019BB5BDCC0E1BB83188B536161CFF *) Line 23585	C++
 	GameAssembly.dll!AnchorModuleScript_CreateAzureAnchor_mC3BA473CF32F9DAB71CB1DBA83ED14F3FE3E3E31(AnchorModuleScript_t210CBF8D6595B477D0C0B06ABD001FA2FB036C59 * __this, GameObject_tBD1244AD56B4E59AAD76E5E7C9282EC5CE434F0F * ___theObject0, const MethodInfo * method) Line 25781	C++
 	GameAssembly.dll!Action_1_Invoke_mB86FC1B303E77C41ED0E94FC3592A9CF8DA571D5_gshared(Action_1_t551A279CEADCF6EEAE8FA2B1E1E757D0D15290D0 * __this, Il2CppObject * ___obj0, const MethodInfo * method) Line 16267	C++
 	GameAssembly.dll!InvokableCall_1_Invoke_mD81223A0EAE1E7988803B8F92DB9090ECFA259FE_gshared(InvokableCall_1_t4C25D83F8CA99D8F1156E28315A6AD077D0951BC * __this, Il2CppObject * ___args00, const MethodInfo * method) Line 31985	C++
 	[Inline Frame] GameAssembly.dll!VirtActionInvoker1<ObjectU5BU5D_t3C9242B5C88A48B2A5BD9FDA6CD0024E792AF08A *>::Invoke(unsigned int) Line 83	C++
 	GameAssembly.dll!UnityEvent_Invoke_mB2FA1C76256FE34D5E7F84ABE528AC61CE8A0325(UnityEvent_t5C6DDC2FCDF7F5C1808F1DDFBAD27A383F5FE65F * __this, const MethodInfo * method) Line 23525	C++
 	GameAssembly.dll!Interactable_SendOnClick_m3DB4E0BFFC42037E8AE07471E01D31A4A2281499(Interactable_tBD08E2FCD550ED1C36870EA7251ABDE8C25E02E2 * __this, Il2CppObject * ___pointer0, const MethodInfo * method) Line 43757	C++
 	GameAssembly.dll!Interactable_TriggerOnClick_m863A719276FD64CDFCC85B1972191F942E2C3E0B(Interactable_tBD08E2FCD550ED1C36870EA7251ABDE8C25E02E2 * __this, const MethodInfo * method) Line 43723	C++
 	[Inline Frame] GameAssembly.dll!Interactable_SetInputUp_m7F0E0C9C4F70E957F531DE0A514EC9C567FEFFDC(Interactable_tBD08E2FCD550ED1C36870EA7251ABDE8C25E02E2 *) Line 44022	C++
 	GameAssembly.dll!Interactable_OnInputUp_mFC1C9A4B9E2FC36A4FEB9CD013F1FA7931F579AB(Interactable_tBD08E2FCD550ED1C36870EA7251ABDE8C25E02E2 * __this, InputEventData_t4448A1ECF70018591A9050CEC5582EEF07663896 * ___eventData0, const MethodInfo * method) Line 44783	C++
 	[Inline Frame] GameAssembly.dll!InterfaceActionInvoker1<InputEventData_t4448A1ECF70018591A9050CEC5582EEF07663896 *>::Invoke(unsigned int) Line 40	C++
 	GameAssembly.dll!U3CU3Ec_U3C_cctorU3Eb__240_18_m86AC1B64C5F08A197190B8E88ADF1DAF66D2A5DE(U3CU3Ec_tCB1D8CA4BE09C4207199A2A0C520429E5ACC3080 * __this, Il2CppObject * ___handler0, BaseEventData_t46C9D2AE3183A742EDE89944AF64A23DBF1B80A5 * ___eventData1, const MethodInfo * method) Line 4496	C++
 	GameAssembly.dll!AnchorLocatedDelegate_Invoke_m6D3ACC204ADCC92E6345AC304AFE8CFA31FE55C2(AnchorLocatedDelegate_t3B9F02C106148F16565BB7C81CB533E4C2ED136D * __this, Il2CppObject * ___sender0, AnchorLocatedEventArgs_tDF201ADA72EFF06EBC2789523F53294BDCE5D836 * ___args1, const MethodInfo * method) Line 38478	C++
 	GameAssembly.dll!ExecuteEvents_Execute_TisRuntimeObject_m69C612263456A3111F97114B38B8A0E2E16E4347_gshared(GameObject_tBD1244AD56B4E59AAD76E5E7C9282EC5CE434F0F * ___target0, BaseEventData_t46C9D2AE3183A742EDE89944AF64A23DBF1B80A5 * ___eventData1, EventFunction_1_tCDB8D379DD3CEC56B7828A86C5DCF113D208CF8D * ___functor2, const MethodInfo * method) Line 57555	C++
 	GameAssembly.dll!ExecuteEvents_ExecuteHierarchy_TisRuntimeObject_m2E66C1E626886F04E8AEC36183F9E982392C62F3_gshared(GameObject_tBD1244AD56B4E59AAD76E5E7C9282EC5CE434F0F * ___root0, BaseEventData_t46C9D2AE3183A742EDE89944AF64A23DBF1B80A5 * ___eventData1, EventFunction_1_tCDB8D379DD3CEC56B7828A86C5DCF113D208CF8D * ___callbackFunction2, const MethodInfo * method) Line 42975	C++
 	GameAssembly.dll!MixedRealityInputSystem_DispatchEventToObjectFocusedByPointer_TisRuntimeObject_m8B5120CF01C8CC1162427FF59C328E7198A31881_gshared(MixedRealityInputSystem_t8830E025B146E02AA41B1AFE8D3EBE18FF368502 * __this, Il2CppObject * ___mixedRealityPointer0, BaseInputEventData_tBB63D9BEE1678B2CD47272D16449017A2AC4B04A * ___baseInputEventData1, bool ___modalEventHandled2, EventFunction_1_tCDB8D379DD3CEC56B7828A86C5DCF113D208CF8D * ___eventHandler3, const MethodInfo * method) Line 27976	C++
 	GameAssembly.dll!MixedRealityInputSystem_HandleEvent_TisRuntimeObject_m78C70FFA111DDE536E67FB8C5086D8CB919A9B41_gshared(MixedRealityInputSystem_t8830E025B146E02AA41B1AFE8D3EBE18FF368502 * __this, BaseEventData_t46C9D2AE3183A742EDE89944AF64A23DBF1B80A5 * ___eventData0, EventFunction_1_tCDB8D379DD3CEC56B7828A86C5DCF113D208CF8D * ___eventHandler1, const MethodInfo * method) Line 45542	C++
 	[Inline Frame] GameAssembly.dll!GenericVirtActionInvoker2<BaseEventData_t46C9D2AE3183A742EDE89944AF64A23DBF1B80A5 *,EventFunction_1_t9D4CE70550203F6421F30B0AB6BDB5296DF6FDD6 *>::Invoke(const MethodInfo *) Line 96	C++
 	GameAssembly.dll!MixedRealityInputSystem_RaiseOnInputUp_mA1B82FC30EB5E6246FFBCC9D86B4BE363A5B9A40(MixedRealityInputSystem_t8830E025B146E02AA41B1AFE8D3EBE18FF368502 * __this, Il2CppObject * ___source0, unsigned char ___handedness1, MixedRealityInputAction_t21FA9287AC97D00262CA87C0AEF9F92E67203970 ___inputAction2, const MethodInfo * method) Line 35680	C++
 	[Inline Frame] GameAssembly.dll!InterfaceActionInvoker3<Il2CppObject *,unsigned char,MixedRealityInputAction_t21FA9287AC97D00262CA87C0AEF9F92E67203970>::Invoke(unsigned int) Line 127	C++
 	GameAssembly.dll!GenericXRSDKController_UpdateButtonData_mD5BA296A813CBB78176F8EB8D65AB3642568754F(GenericXRSDKController_t11AF783263695F22D97BDFDDD33F5C9D86EB5F49 * __this, MixedRealityInteractionMapping_t0C8EA2AB8DF12A2570FBF18A3A2767354A5AB662 * ___interactionMapping0, InputDevice_tF13BD967109BAB2CF49E1304EDFDA255067A2CDC ___inputDevice1, const MethodInfo * method) Line 11355	C++
 	[Inline Frame] GameAssembly.dll!VirtActionInvoker2<MixedRealityInteractionMapping_t0C8EA2AB8DF12A2570FBF18A3A2767354A5AB662 *,InputDevice_tF13BD967109BAB2CF49E1304EDFDA255067A2CDC>::Invoke(unsigned int) Line 50	C++
 	GameAssembly.dll!GenericXRSDKController_UpdateController_m2CEF1DB951F9334A63E304C68100DE5E96E676C9(GenericXRSDKController_t11AF783263695F22D97BDFDDD33F5C9D86EB5F49 * __this, InputDevice_tF13BD967109BAB2CF49E1304EDFDA255067A2CDC ___inputDevice0, const MethodInfo * method) Line 10948	C++
 	GameAssembly.dll!WindowsMixedRealityXRSDKArticulatedHand_UpdateController_mD6000EF593CC481BACA0ACBF73BC3CBCAF4D967F(WindowsMixedRealityXRSDKArticulatedHand_tD83E080D756E06E2206428E2AC23750450145769 * __this, InputDevice_tF13BD967109BAB2CF49E1304EDFDA255067A2CDC ___inputDevice0, const MethodInfo * method) Line 7248	C++
 	[Inline Frame] GameAssembly.dll!VirtActionInvoker1<InputDevice_tF13BD967109BAB2CF49E1304EDFDA255067A2CDC>::Invoke(unsigned int) Line 72	C++
 	GameAssembly.dll!XRSDKDeviceManager_Update_mA17479E8D224D569841E3F4C5794DC54DD7D275E(XRSDKDeviceManager_t58EE139DC1B0D6BBC77E6475CF21D76AFEEB506B * __this, const MethodInfo * method) Line 12407	C++
 	GameAssembly.dll!WindowsMixedRealityDeviceManager_Update_m2885CD4E1869B358E5CEB44C9B51E448773867B7(WindowsMixedRealityDeviceManager_t7EB44B47A5A206AB6E1B29F6D98D4FD02B7F0DB1 * __this, const MethodInfo * method) Line 6408	C++
 	[Inline Frame] GameAssembly.dll!InterfaceActionInvoker0::Invoke(unsigned int) Line 94	C++
 	GameAssembly.dll!BaseDataProviderAccessCoreSystem_Update_m3B6BA0A2E31D4238DE126F96C652A2B0882E4F2B(BaseDataProviderAccessCoreSystem_tEC30D51F31BA37D15DA66B7E10C2FC3AEA41F535 * __this, const MethodInfo * method) Line 15148	C++
 	[Inline Frame] GameAssembly.dll!InterfaceActionInvoker0::Invoke(unsigned int) Line 104	C++
 	GameAssembly.dll!U3CU3Ec_U3CUpdateAllServicesU3Eb__64_0_m4E00630EBD0A327A3D713131F8203DC870966ACC(U3CU3Ec_t3327AA19F587E338AC0F66EA8B7388FDC02D37E8 * __this, Il2CppObject * ___service0, const MethodInfo * method) Line 21096	C++
 	GameAssembly.dll!Action_1_Invoke_mB86FC1B303E77C41ED0E94FC3592A9CF8DA571D5_gshared(Action_1_t551A279CEADCF6EEAE8FA2B1E1E757D0D15290D0 * __this, Il2CppObject * ___obj0, const MethodInfo * method) Line 16267	C++
 	[Inline Frame] GameAssembly.dll!Action_1_Invoke_m65E0C1FCBBBEB75F74968FC7105189BBB02CC8E1(Action_1_t54997B2C4A5E5A4FD5491044AF94FE0A1ACEFF5C *) Line 12479	C++
 	GameAssembly.dll!MixedRealityToolkit_ExecuteOnAllServicesInOrder_m3DCEB6CF248CD76955FAEF749D2252C5242FB0EA(MixedRealityToolkit_t0719417BE57FB26F681DB3A09ABA664135D52D90 * __this, Action_1_t54997B2C4A5E5A4FD5491044AF94FE0A1ACEFF5C * ___execute0, const MethodInfo * method) Line 19677	C++
 	GameAssembly.dll!MixedRealityToolkit_UpdateAllServices_m028E2C36E3C6167923B7CB647FD17DB7F05EDFC5(MixedRealityToolkit_t0719417BE57FB26F681DB3A09ABA664135D52D90 * __this, const MethodInfo * method) Line 19063	C++
 	GameAssembly.dll!MixedRealityToolkit_Update_m0CDAD4F096D7184695973258D89BE15ECB53D8D6(MixedRealityToolkit_t0719417BE57FB26F681DB3A09ABA664135D52D90 * __this, const MethodInfo * method) Line 17742	C++
 	GameAssembly.dll!RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void(*)() methodPointer, const MethodInfo * methodMetadata, void * obj, void * * args) Line 49134	C++
 	GameAssembly.dll!il2cpp::vm::Runtime::Invoke(const MethodInfo * method, void * obj, void * * params, Il2CppException * * exc) Line 545	C++
 	[External Code]	
'

I tried to debug it by wrapping the function AnchorModuleScript.CreateAzureAnchor with a try-catch, in order to catch the error and debug it, but the app is crashing anyways, so I wonder if the error pops up before the function is called (but yet, after clicking the button).

I'm not experienced in Unity and Hololens development so I apologize for any missing information, and I'm of course available to provide more info if needed. Any help is appreciated.

Thank you in advance!

![temp](https://user-images.githubusercontent.com/42271354/105424756-3f0ab880-5c48-11eb-9481-9e208c15cbe6.png)

**Comment by sana2024** [comment]
I have the same problem, did you find any solution??

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
