### ISSUE TITLE
Hololens2 Azure Spatial Anchors Tutorial Crash

### ISSUE THREAD

**Issue by mattbolgercsiro** [microsoft/MixedRealityLearning#34]
Trying to follow the [Microsoft Azure Spatial Anchors tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02) (even after it was recently updated) but the Release build of the project crashes on launch on the device (just after the Unity splash screen). Interestingly a Debug build of the same project seems to launch ok. 

I've been able to build, deploy, test both the basic [Hololen2 tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-01) and the [ASA Samples](https://github.com/Azure/azure-spatial-anchors-samples) as well as some custom projects so don't think this is a general development or deployment issue. 

Have others been able to follow this tutorial and successfully deploy to a device recently and/or is there any suggestions to diagnose the issue further? 

Setup and Unity packages used (as per the tutorial and linked instructions):

 - Hololens OS (up to date): 19041.1136
 - Unity 2019.4.19f1
 - com.microsoft.azure.spatial-anchors-sdk.core@2.7.1
 - com.microsoft.azure.spatial-anchors-sdk.windows@2.7.1 
 - MRTK Foundation - 2.5.3 from the basic tutorial series (MRTK Package Tool) 
 - AR Foundation: 3.1.3 
 - Windows Mixed Reality: 4.2.1 (downgrade from 4.2.3?)
 - MRTK.HoloLens2.Unity.Tutorials.Assets.GettingStarted.2.4.0.unitypackage
 - MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.4.0.unitypackage

Note: MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.4.0.unitypackage actually links to a new 2.5.3 package (https://github.com/microsoft/MixedRealityLearning/releases/tag/azure-spatial-anchors-v2.5.3) however the version file in this package still has 2.4.0??

Exception thrown at 0x00000226E0FBCC40 in Workspace Hololens2 MRTK.exe: 0xC0000005: Access violation executing location 0x00000226E0FBCC40.

**Comment by MattAU** [comment]
I think through process of elimination this is somehow caused by the DebugWindow prefab's BoundsControl component (as provided in the Tutorials.Assets.AzureSpatialAnchors package from the tutorial). If I disable this one component on the instance of this in the scene then the application loads.

**Comment by mattbolgercsiro** [comment]
I think through process of elimination this is somehow caused by the DebugWindow prefab's BoundsControl component (as provided in the Tutorials.Assets.AzureSpatialAnchors package from the tutorial). If I disable this one component on the instance of this in the scene then the application loads.

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
