### ISSUE TITLE
Able to Create Anchor, but unable to search Anchor

### ISSUE THREAD

**Issue by virtualxmy** [microsoft/MixedRealityLearning#35]
Last year around Nov 2020 still work fine.  But today i try again, it having issue.  I was able to create anchor, however when search for anchor, it took forever to find anchor.  
I tried to change Azure spatial Anchor SDK to 2.5.0 and AR Foundation to 3.1.3 still doesn't work.  Any idea why is this happening?
You help Much appreciated 

![20210226_130926_HoloLens 1](https://user-images.githubusercontent.com/79683442/109259430-2a1cd880-7837-11eb-9440-3ebb1aa0c777.jpg)

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
