### ISSUE TITLE
MRTK.Tutorials.AzureSpatialAnchors for ASA SDK 2.9

### ISSUE THREAD

**Issue by JoSharon** [microsoft/MixedRealityLearning#38]
We use Unity 2020.3 with Unity XR Plug-in Framework, and we want to use  Multi-user capabilities,
so we use ASA SDK 2.9  
and import these asset:
MRTK.HoloLens2.Unity.Tutorials.Assets.GettingStarted.2.4.0.unitypackage
MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.4.0.unitypackage
MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.4.0.unitypackage

console shows:
Assets\MRTK.Tutorials.AzureSpatialAnchors\Scripts\AnchorModuleScript.cs(128,40): error CS0029: Cannot implicitly convert type 'System.Threading.Tasks.Task<System.IntPtr>' to 'System.IntPtr'
Assets\MRTK.Tutorials.AzureSpatialAnchors\Scripts\AnchorModuleScript.cs(396,64): error CS0234: The type or namespace name 'WorldAnchor' does not exist in the namespace 'UnityEngine.XR.WSA' (are you missing an assembly reference?)

is there any solution?
If tutotial assets 2.4.0 do not support ASA SDK 2.9, do you have toturial assets for ASA SDK 2.9?

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
