### ISSUE TITLE
Error when using ASA 2.10.2 and MRTK 2.7.2  for Android builds

### ISSUE THREAD

**Issue by havokentity** [microsoft/MixedRealityLearning#47]
I am getting this error when I add MRTK 2.7.2 to a Unity project which has ASA 2.10.2 whenenever I try to do an Android build.

Library\PackageCache\com.microsoft.azure.spatial-anchors-sdk.core@0d9691ef23ae-1634109003085\Runtime\Scripts\SpatialAnchorExtensions.cs(17,17): error CS0234: The type or namespace name 'MixedReality' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

Can someone please help?

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
