### ISSUE TITLE
PC Holographic Remoting not preview rendering

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedRealityLearning#48]
The PC Holographic Remoting sample runs perfectly on Windows Standalone build. While on UWP build, the remoting part works, i.e. the hololens is showing the rendering, but the app itself is not updating the rendering (the preview content is not updating).

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
