### ISSUE TITLE
AzureStorageForUnity Package Contains Newtonsoft.Json.Dll that conflicts with MRTK Packages

### ISSUE THREAD

**Issue by ARGs-code** [microsoft/MixedRealityLearning#49]
**Issue**
Importing the AzureStorageForUnity.package into a Unity Project with Mixed Reality Toolkit creates Compiler errors. If you remove the dll that comes with the AzureStorageForUnity.package you get errors because it references strong named Newtonsoft.Json assembly references for 10.0.0.0 and Mixed Reality Toolkit Package forces 12.0.0.0.

**To recreate**
Make a Unity Project in Unity 2020.3.x
Import Mixed Reality Toolkit from Microsoft Using the MRTK Feature Discovery Tool
Notice you have no errors after completing setup

Import AzureStorageForUnity.package

Notice Compiler Errors from Newtonsoft.Json.dll conflicts.

"Assets\MRTK.Tutorials.AzureCloudServices\Scripts\Dtos\ImageElement.cs(7,10): error CS0433: The type 'JsonPropertyAttribute' exists in both 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' and 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'"

Can't remove the .dll that is included with the MRTK Package Manager because it's managed by unity's package system. If remove or modify the .dll that comes with the AzureStorageForUnity.package then you get the following compiler error.

"Assembly 'Assets/Azure Storage/Plugins/Microsoft.WindowsAzure.Storage.dll' will not be loaded due to errors:
Microsoft.WindowsAzure.Storage references strong named Newtonsoft.Json Assembly references: 10.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Issue arose from following the tutorial at this location:
https://docs.microsoft.com/en-us/learn/modules/azure-cloud-services-tutorials/3-exercise-azure-cloud-services-for-hololens-2

**Comment by Edouard99** [comment]
Hi, were you able to find a fix ? I am trying to use azure storage and I am running into the same error, I thought about deactivate the version control but I am not sure if this won't cause trouble for the deployment on Hololens

**Comment by AMollis** [comment]
Marking this stale issue as "won't fix". 

If relevant, please try out the new MRTK3 tutorial samples. @ https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials.

If the new MRTK3 samples don't have a relevant fix for your problem, please open a new issue.  

Thank you.
