### ISSUE TITLE
MRTK3 Learning Path - compilation errors in Unity

### ISSUE THREAD

**Issue by chenruijia120** [microsoft/MixedRealityLearning#81]
## Describe the bug

Hi! I got similar errors with https://learn.microsoft.com/en-us/answers/questions/1392297/i-am-getting-compilation-errors-in-unity-that-nonn. Library\PackageCache\org.mixedrealitytoolkit.uxcore@45c07beda63c\Experimental\NonNativeKeyboard\TMPInputFieldNonNativeKeyboardTrigger.cs(67,42): error CS0103: The name 'NonNativeKeyboard' does not exist in the current context

I am using Unity 2023.1.17f1 and Windows 11 22H2. I followed the instructions here: https://learn.microsoft.com/en-us/training/modules/learn-mrtk-tutorials/1-5-exercise-configure-resources. Could you please help me?
## To reproduce

I followed the instructions here: https://learn.microsoft.com/en-us/training/modules/learn-mrtk-tutorials/1-5-exercise-configure-resources to import the package

## Expected behavior

Unity cannot detect NonNativeKeyboard.cs file.

## Screenshots
<img width="1138" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/55024350/0f11486a-3fee-45a2-97cb-24e773c000d9">
<img width="865" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/55024350/28422c69-c4ff-4ff8-97bd-46fafb1661ee">

## Your setup (please complete the following information)

- Unity Version 2021.3.31f1
- MRTK Version or Commit [v3.1.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
@chenruijia120 ... I've moved this issue to our Learning Path repository for MRTK3, https://github.com/microsoft/MixedRealityLearning

We'll follow-up here.

@marlenaklein-msft , can help @chenruijia120  out?  Is there a step missing in the learning paths?

**Comment by marlenaklein-msft** [comment]
Hi @chenruijia120, is this setting up a new MRTK3 project from scratch? 

I haven't been able to repro the error. Just to make sure it is not a weirdness with the library, could you try closing the Unity project and deleting the Library folder in your project? 

![image](https://github.com/microsoft/MixedRealityLearning/assets/125413876/fef1578e-a6b4-43c2-8e27-65931a51cac9)

Then reopen the project. If you still see the error, could you share your **Packages > manifest.json** file?

**Comment by chenruijia120** [comment]
Thank you for your quick response! I found the problem: I accidentally installed MRTK2 and MRTK3 at the same time. It has been solved. Thanks again!

**Comment by marlenaklein-msft** [comment]
Great, glad you found the problem!

**Comment by AMollis** [comment]
Closing issue since @chenruijia120  found their error.  

Projects can't have both MRTK2 and MRTK3 in the same project.

**Comment by mendax1234** [comment]
> Thank you for your quick response! I found the problem: I accidentally installed MRTK2 and MRTK3 at the same time. It has been solved. Thanks again!

Hi, I have run into the same issue. So, your solution is to delete MRTK2 right?

[Edited]:
Solved. I have installed the Mixed Reality Toolkit ... 2.8.3 version by accident. After deleting these packages, these errors fly off!

**Comment by m-1007** [comment]
Hi @mendax1234, I also have the same issue. How did you solve this issue. I am also using the 2.8.3 version. Which other version should I use to fix this issue?

**Comment by mendax1234** [comment]
> Hi @mendax1234, I also have the same issue. How did you solve this issue. I am also using the 2.8.3 version. Which other version should I use to fix this issue?

My solution is to use MRTK2 instead of using MRTK3.
